### PR TITLE
Update release files 12 November 2024

### PR DESCRIPTION
**Pull request by matentzn**

### CODE REVIEW

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
Looking through the commits to `master` since the last release, I expected to see 'has symbol' #167 here, but I don't. Maybe 'annotation-properties' needs to be rebuilt?

I do see #168 and #178, which is good.

**Comment by matentzn** [comment]
> Looking through the commits to master since the last release, I expected to see 'has symbol' https://github.com/information-artifact-ontology/ontology-metadata/pull/167 here, but I don't. Maybe 'annotation-properties' needs to be rebuilt?

Oops yea, forgot to rerun the templates workflow.

@zhengj2007 @jamesaoverton should be ready now!

**Review by jamesaoverton — APPROVED** [review]

**Comment by jamesaoverton** [comment]
Now I see the new terms in the OWL files but not the OBO files. Is that expected?

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
Missing new annotation property 'has symbol' in OBO format OMO. Need to be updated.

**Review by zhengj2007 — APPROVED** [review]

**Comment by jamesaoverton** [comment]
> I would suggest we merge this here because the problem was always present.

Agreed -- the OBO-format releases never had any annotation properties, so no big loss.

**Pull request merged**
