### PR TITLE
Create annotation_properties.tsv for APs moving forward

### PR DESCRIPTION
**Pull request by matentzn**
fixes #92

### CODE REVIEW

**Review by zhengj2007 — COMMENTED** [review]
Looks good except dc:contributor that requires ORCID. Not sure how we deal when the contributor is a group or organization. For example, contributor to 'alternative label' is 'OBO Operations committee'.

**Comment by StroemPhi** [comment]
For organizations either use [ROR ](https://ror.org/) where possible and else make a Wikidata entry?

**Comment by matentzn** [comment]
Absolutely, 

1. ORCID for people
2. ROR for orgs
3. Wikidata for people w/o ORCIDs and orgs w/o ROR

**Comment by matentzn** [comment]
cc @anitacaron use this for #123

**Pull request merged**
