### PR TITLE
Adding defined-by-construct

### LINKED ISSUE #85: NTR: defined_by_construct
This property would link an annotation property to a SPARQL CONSTRUCT query which is meant to provide semantics for a shortcut relation, for example `never_in_taxon`. See https://github.com/ontodev/robot/issues/963

I'm open to better labels for this relation.

### PR DESCRIPTION
**Pull request by matentzn**
fixes #85

cc @balhoff

### CODE REVIEW

**Comment by balhoff** [comment]
@matentzn @zhengj2007 could this be merged?

**Comment by matentzn** [comment]
For your purposes, do not worry about it: The ID will be merged, I will see to it. Are you in a rush to get this in omo.owl? We are developing a process atm to do this, and it will be done in 3 weeks or so.

**Comment by balhoff** [comment]
Just trying to move things along, since we have several things to do:
- Update https://github.com/ontodev/robot/pull/964 with this ID
- Merge this and make OMO release
- Release new ROBOT
- Update ROBOT in ODK; release ODK
- Add CONSTRUCT definitions to RO
- Make RO release
- Update ontology pipelines

**Comment by matentzn** [comment]
@zhengj2007 please review so we can get this in! I changed term tracker item to IAO and added an example of usage.

**Review by zhengj2007 — APPROVED** [review]

**Pull request merged**
