### PR TITLE
Add INN synonym type

### LINKED ISSUE #149: NTR: `International Nonproprietary Name`
> Not doing country specific for the generic property sounds good to me.
>
> I like the idea of 'layperson synonym' but the label bothers me, e.g. paracetamol/acetaminophen is really the name used by pharmacists etcs, see https://en.wikipedia.org/wiki/Paracetamol#Naming. 
>
> What about something similar to https://en.wikipedia.org/wiki/International_nonproprietary_name? I think that may be what we are looking for here.

_Originally posted by @mcourtot in https://github.com/information-artifact-ontology/ontology-metadata/issues/148#issuecomment-1740773560_
            

As a follow-up to #148, I also want to add a synonym type for INNs, which are also used in ChEBI and I think need a bit less discussion than brand names

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #149

This PR adds a synonym type *International Nonproprietary Name* (OMO:0003010) This is mapped in the SSSOM file to the ChEBI hash URI http://purl.obolibrary.org/obo/chebi#INN 

One question for @matentzn: I would like to add a synonym for this synonym type for its abbreviation (INN). Is it more work than its worth to extend the template to enable this?

### CODE REVIEW

**Comment by cthoyt** [comment]
@matentzn there are already many very specific synonyms floating around in OBO world, and they need just as much standardization love as the others.

If there's a specific issue with using a hierarchy to group synonym types, then I can remove this, but the point is that there are several other chemical synonym types that are relevant including the ones discussed in #148 and more (e.g., IUPAC)

**Comment by cthoyt** [comment]
@mcourtot might be able to comment in the mean time

**Comment by balhoff** [comment]
> Have you tried nested synonym types in OBO format ontologies? I never have. @balhoff should also take a look at this, 

@matentzn I'm not sure I understand the question. @cthoyt could you write out an example?

**Comment by matentzn** [comment]
Inn sub chemicalsyntype sub oio:synonymtype - that ok for the current obo format parser?

**Comment by matentzn** [comment]
If you want to move this forward you have three options:

1. Either get an answer from Jim or Chris on whether the OBO format parser permits a nested synonym type hierarchy
2. Write a test that proves that it is allowed 
3. remove the chemical synonym property

**Comment by cthoyt** [comment]
@matentzn you hashtag handled me :p. you know that I will always choose the option that gets the PR in fastest. We can move the discussion about adding structure within this hierarchy to a new issue.

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
This PR can be merged by anyone from Wednesday 10am PT and is open for reviews until then.

**Pull request merged**
