### PR TITLE
add individual: out of scope

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close https://github.com/information-artifact-ontology/ontology-metadata/issues/77

### CODE REVIEW

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
@cmungall @zhengj2007 

Should we be using OMO namespace

**Comment by zhengj2007** [comment]
It sounds good to me to use OMO prefix.

Is any issue tracker associated with this pull request?

**Comment by nicolevasilevsky** [comment]
I did not create a ticket @zhengj2007, would you like me to?

We need this for Mondo.

**Comment by zhengj2007** [comment]
@nicolevasilevsky Would be nice to have an issue tracker associated with the changes and  using 'ontology term requester' and 'term tracker item' annotations with the term to indicate who request the term and details about it. So, we can trace back if anyone have questions. Thanks!

**Comment by nicolevasilevsky** [comment]
@zhengj2007 done!

**Comment by zhengj2007** [comment]
@nicolevasilevsky Would you like to update the annotations associated with the new individual and add it to 'obsolescence reason specification' equivalent axiom in the OWL file?

**Comment by alanruttenberg** [comment]
It doesn't seem that 'out of scope' would be a reason for obsolescence on
its own unless the class was duplicated in another ontology, in which case
the duplication would be the reason for obsoleting. Otherwise an
out-of-scope term would migrate to the appropriate ontology, no?

**Comment by nicolevasilevsky** [comment]
@alanruttenberg this is for the Mondo Disease Ontology, where we bring in terms from other sources but sometimes they are considered out of scope for Mondo but they still exist in another source ontology.

**Comment by alanruttenberg** [comment]
Is the term brought in with the original URL?

**Comment by nicolevasilevsky** [comment]
All the terms in Mondo have a Mondo ID and we add database cross references to the source terms

**Comment by alanruttenberg** [comment]
I see. I don't think I want to know why MONDO would mint a new IRI for an existing term...

**Comment by nicolevasilevsky** [comment]
@zhengj2007 i made your requested changes

**Comment by matentzn** [comment]
I just lost my vote @alanruttenberg against numeric IDs but this PR is a good illustration of why we had the debate in #82 

I need to literally google 3 (!) APs now just to see whether @nicolevasilevsky used the correct APs for the term.

image


Anyways. I know. Better diff tools will solve it. That was not the point though!

**Review by matentzn — APPROVED** [review]

**Pull request merged**
